#stage 1 - build project
FROM maven:3-amazoncorretto-21 AS builder
WORKDIR /app
COPY pom.xml pom.xml
COPY src src
 
RUN mvn install -Dmaven.test.skip=true
 
#stage 2 - run project
FROM amazoncorretto:21-al2-jdk
WORKDIR /app
COPY --from=builder /app/target/local4localEU-0.0.1-SNAPSHOT.jar .
 
EXPOSE 8080/tcp
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=development", "-Duser.dir=/app", "-Dja", "-jar", "/app/local4localEU-0.0.1-SNAPSHOT.jar"]